//-----------------------------------------------------------------------------
//
// Copyright (C) 2013 David Hill
//
// See COPYING for license information.
//
//-----------------------------------------------------------------------------
//
// List of all string table constants.
//
//-----------------------------------------------------------------------------

GDCC_StringList(ACSE, "ACSE")
GDCC_StringList(Action, "Action")
GDCC_StringList(AddI_W, "AddI_W")
GDCC_StringList(AddU_W, "AddU_W")
GDCC_StringList(AndU_W, "AndU_W")
GDCC_StringList(AsmFunc, "AsmFunc")
GDCC_StringList(Call, "Call")
GDCC_StringList(Casm, "Casm")
GDCC_StringList(Cjmp_Nil, "Cjmp_Nil")
GDCC_StringList(Cjmp_Tru, "Cjmp_Tru")
GDCC_StringList(CmpI_EQ_W, "CmpI_EQ_W")
GDCC_StringList(CmpU_EQ_W, "CmpU_EQ_W")
GDCC_StringList(CmpI_GE_W, "CmpI_GE_W")
GDCC_StringList(CmpU_GE_W, "CmpU_GE_W")
GDCC_StringList(CmpI_GT_W, "CmpI_GT_W")
GDCC_StringList(CmpU_GT_W, "CmpU_GT_W")
GDCC_StringList(CmpI_LE_W, "CmpI_LE_W")
GDCC_StringList(CmpU_LE_W, "CmpU_LE_W")
GDCC_StringList(CmpI_LT_W, "CmpI_LT_W")
GDCC_StringList(CmpU_LT_W, "CmpU_LT_W")
GDCC_StringList(CmpI_NE_W, "CmpI_NE_W")
GDCC_StringList(CmpU_NE_W, "CmpU_NE_W")
GDCC_StringList(Cnat, "Cnat")
GDCC_StringList(Cpy, "Cpy")
GDCC_StringList(Cspe, "Cspe")
GDCC_StringList(Death, "Death")
GDCC_StringList(Disconnect, "Disconnect")
GDCC_StringList(DivI_W, "DivI_W")
GDCC_StringList(DivX_W, "DivX_W")
GDCC_StringList(Empty, "Empty")
GDCC_StringList(Enter, "Enter")
GDCC_StringList(ExtACS, "ExtACS")
GDCC_StringList(ExtASM, "ExtASM")
GDCC_StringList(ExtC, "ExtC")
GDCC_StringList(ExtCXX, "ExtCXX")
GDCC_StringList(ExtDS, "ExtDS")
GDCC_StringList(Far, "Far")
GDCC_StringList(Fixed, "Fixed")
GDCC_StringList(Float, "Float")
GDCC_StringList(Funct, "Funct")
GDCC_StringList(Function, "Function")
GDCC_StringList(GblArr, "GblArr")
GDCC_StringList(GblArs, "GblArs")
GDCC_StringList(GblReg, "GblReg")
GDCC_StringList(Gen, "Gen")
GDCC_StringList(IntC, "IntC")
GDCC_StringList(IntCXX, "IntCXX")
GDCC_StringList(InvU_W, "InvU_W")
GDCC_StringList(Jump, "Jump")
GDCC_StringList(LangACS, "LangACS")
GDCC_StringList(LangASM, "LangASM")
GDCC_StringList(LangAXX, "LangAXX")
GDCC_StringList(LangC, "LangC")
GDCC_StringList(LangCXX, "LangCXX")
GDCC_StringList(LangDS, "LangDS")
GDCC_StringList(Lightning, "Lightning")
GDCC_StringList(Lit, "Lit")
GDCC_StringList(Loc, "Loc")
GDCC_StringList(LocArs, "LocArs")
GDCC_StringList(LocReg, "LocReg")
GDCC_StringList(MageCraft, "MageCraft")
GDCC_StringList(MapArr, "MapArr")
GDCC_StringList(MapArs, "MapArs")
GDCC_StringList(MapReg, "MapReg")
GDCC_StringList(MgC_NTS, "MgC_NTS")
GDCC_StringList(ModI_W, "ModI_W")
GDCC_StringList(Move_W, "Move_W")
GDCC_StringList(MulI_W, "MulI_W")
GDCC_StringList(MulX_W, "MulX_W")
GDCC_StringList(Multi, "Multi")
GDCC_StringList(Native, "Native")
GDCC_StringList(NegI_W, "NegI_W")
GDCC_StringList(None, "None")
GDCC_StringList(Nop, "Nop")
GDCC_StringList(NotU_W, "NotU_W")
GDCC_StringList(Nul, "Nul")
GDCC_StringList(Open, "Open")
GDCC_StringList(OrIU_W, "OrIU_W")
GDCC_StringList(OrXU_W, "OrXU_W")
GDCC_StringList(Point, "Point")
GDCC_StringList(Respawn, "Respawn")
GDCC_StringList(Retn, "Retn")
GDCC_StringList(Return, "Return")
GDCC_StringList(Script, "Script")
GDCC_StringList(ScriptI, "ScriptI")
GDCC_StringList(ScriptS, "ScriptS")
GDCC_StringList(ShLU_W, "ShLU_W")
GDCC_StringList(ShRI_W, "ShRI_W")
GDCC_StringList(Special, "Special")
GDCC_StringList(Stk, "Stk")
GDCC_StringList(StrArr, "StrArr")
GDCC_StringList(StrArs, "StrArs")
GDCC_StringList(SubI_W, "SubI_W")
GDCC_StringList(SubU_W, "SubU_W")
GDCC_StringList(Swap_W, "Swap_W")
GDCC_StringList(Unloading, "Unloading")
GDCC_StringList(Vaa, "Vaa")
GDCC_StringList(ValueGlyph, "ValueGlyph")
GDCC_StringList(ValueRoot, "ValueRoot")
GDCC_StringList(WldArr, "WldArr")
GDCC_StringList(WldArs, "WldArs")
GDCC_StringList(WldReg, "WldReg")
GDCC_StringList(ZDoom, "ZDoom")
GDCC_StringList(block, "block")
GDCC_StringList(ctype, "ctype")
GDCC_StringList(label, "label")
GDCC_StringList(linka, "linka")
GDCC_StringList(retrn, "retrn")
GDCC_StringList(stype, "stype")
GDCC_StringList(valueInt, "valueInt")

GDCC_StringList(ERR_UntermString, "unterminated string literal")

// Simple tokens.
GDCC_StringList(TOK_Comma, ",")
GDCC_StringList(TOK_Equal, "=")

// Paired tokens.
GDCC_StringList(TOK_BraceO, "{")
GDCC_StringList(TOK_BraceC, "}")
GDCC_StringList(TOK_BrackO, "[")
GDCC_StringList(TOK_BrackC, "]")
GDCC_StringList(TOK_ParenO, "(")
GDCC_StringList(TOK_ParenC, ")")

// Whitespace tokens.
GDCC_StringList(TOK_EOL, "\n")

#undef GDCC_StringList

// EOF

